title: ax
email: ax@slackware.eu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ax" # the subpath of your site, e.g. /blog
url: "aicsx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aicsx

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed

# config theme

header_pages:
  - index.md
  - scrot.md
  - contact.md

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

footer: 'follow me on <a href="https://github.com/aicsx">Github/aicsx</a>'
