title: ax
email: ax@slackware.eu
description: >- # this means to ignore newlines until "baseurl:"
  ax - My Personal Page ex/linuax
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aicsx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aicsx

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-seo-tag

# config theme

header_pages:
  - index.md
  - scrot.md
  - contact.md

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

footer: 'follow me on <a href="https://github.com/aicsx">Github/aicsx</a>'
